export const Constants = {
    newQuestion : {
        'QUESTION_ID': 1,
        'QUESTION': '',
        'DESCRIPTION': null,
        'HELP_LINK': null,
        'ANSWER_TYPE': 'Radio',
        'ANSWER_LENGTH': null,
        'NO_OF_ANSWERS': 1,
        'LOOKUP_TYPE': null,
        'LOOKUP_NAME': null,
        'LOOKUP_FIELD': null,
        'GROUP_NAME': 'G0',
        'GROUP_LABEL': null,
        'HAS_CONDITION': 'N',
        'SHOW_QUESTION': false,
        'COMPLETION_FLAG': null,
        'ANSWERS': {},
        'QUESTIONNAIRE_ID': null,
        'ATTACHMENT_ID': null,
        'QUESTIONNAIRE_ANSWER_ID': null,
        'QUESTIONNAIRE_ANSWER_HEADER_ID': null,
        'ANSWER_NUMBER': null,
        'ANSWER_LOOKUP_CODE': null,
        'EXPLANATION': null,
        'UPDATE_TIMESTAMP': null,
        'UPDATE_USER': null,
        'AC_TYPE': 'I',
        'HIDE_QUESTION': false,
        'QUESTION_NUMBER': null,
        'QUESTION_VERSION_NUMBER': null,
        'PARENT_QUESTION_ID': null,
        'NEW_VALUE': true
    },
    newOption : {
        'QUESTION_OPTION_ID': null,
        'OPTION_NUMBER': null,
        'QUESTION_ID': null,
        'EXPLANTION_LABEL': null,
        'OPTION_LABEL': null,
        'REQUIRE_EXPLANATION': null,
        'AC_TYPE': 'I',
    },
    newCondition : {
        'GROUP_NAME': null,
        'CONDITION_TYPE': 'EQUALS',
        'QUESTION_CONDITION_ID': null,
        'CONDITION_VALUE': null,
        'QUESTION_ID': null,
        'AC_TYPE': 'I',
    },
    editorConfig: {
        'editable': true,
        'spellcheck': true,
        'height': '100px',
        'minHeight': '0',
        'width': 'auto',
        'minWidth': '0',
        'translate': 'yes',
        'enableToolbar': true,
        'showToolbar': true,
        'placeholder': 'Enter text here...',
        'imageEndPoint': '',
        'toolbar': [
            ['bold', 'italic', 'underline', 'superscript', 'subscript'],
            ['fontName', 'fontSize', 'color'],
            ['justifyLeft', 'justifyCenter', 'justifyRight'],
            ['paragraph', 'blockquote', 'removeBlockquote', 'horizontalLine', 'orderedList', 'unorderedList'],
        ]
      },
      subModuleList: [
          {'moduleId': 3, 'subModuleId': 1, 'label': 'Proposal Budget'},
          {'moduleId': 3, 'subModuleId': 2, 'label': 'S2S Questionnaires'},
          {'moduleId': 3, 'subModuleId': 3, 'label': 'Proposal Person Certification'},
          {'moduleId': 7, 'subModuleId': 1, 'label': 'Amendment / Renewal'},
          {'moduleId': 7, 'subModuleId': 2, 'label': 'Protocol Submission'},
          {'moduleId': 7, 'subModuleId': 3, 'label': 'Renewal'},
          {'moduleId': 7, 'subModuleId': 4, 'label': 'Amendment'},
          {'moduleId': 8, 'subModuleId': 1, 'label': 'Award'},
          {'moduleId': 9, 'subModuleId': 1, 'label': 'Amendment / Renewal'},
          {'moduleId': 9, 'subModuleId': 3, 'label': 'Renewal'},
          {'moduleId': 9, 'subModuleId': 4, 'label': 'Amendment'},
          {'moduleId': 9, 'subModuleId': 5, 'label': 'Continuation'},
      ],
      newUsage : {
        'QUESTIONNAIRE_USAGE_ID': null,
        'AC_TYPE': 'I',
        'MODULE_ITEM_CODE': null,
        'MODULE_SUB_ITEM_CODE': null,
        'QUESTIONNAIRE_ID': null,
        'QUESTIONNAIRE_LABEL': null,
        'IS_MANDATORY': false,
        'RULE_ID': null
      }
};

